# Generated by Django 4.1.3 on 2022-11-13 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('maxnum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('charge', models.FloatField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('phone', models.TextField(max_length=11)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('birth', models.DateField()),
                ('sex', models.BooleanField()),
                ('phone', models.TextField(max_length=11)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.owner'),
        ),
    ]
