# Generated by Django 4.1.3 on 2022-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
