# Generated by Django 4.1.3 on 2022-11-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.tenant')),
            ],
        ),
    ]
