# Generated by Django 4.1.3 on 2022-11-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='username',
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('identity', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.owner')),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.tenant')),
            ],
        ),
    ]
