# Generated by Django 4.1.3 on 2022-11-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_tenant_renting_alter_tenant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='charge',
            new_name='price',
        ),
    ]
