# Generated by Django 4.1.3 on 2022-11-15 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_rename_charge_house_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]))]),
            preserve_default=False,
        ),
    ]
