# Generated by Django 4.1.3 on 2022-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_remove_house_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
