# Generated by Django 4.1.3 on 2022-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_relation_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
