# Generated by Django 4.1.3 on 2022-11-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_remove_account_pay_remove_house_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.account'),
        ),
        migrations.AddField(
            model_name='relation',
            name='fee',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='own_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='ten_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.house'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
