# Generated by Django 4.1.3 on 2022-11-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_relation_account_relation_fee_relation_own_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='account',
        ),
        migrations.AlterField(
            model_name='relation',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.house'),
        ),
    ]
