# Generated by Django 4.1.3 on 2022-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_remove_relation_own_paid_house_can_be_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
