# Generated by Django 4.1.3 on 2022-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='house_shown',
            field=models.BooleanField(default=False),
        ),
    ]
