# Generated by Django 4.1.3 on 2022-11-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_relation_house_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='house_shown',
        ),
    ]
